FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-focal
MAINTAINER support@oneidentity.com

RUN groupadd -r safeguard \
    && useradd -r -g safeguard -s /bin/bash safeguard \
    && mkdir -p /home/safeguard \
    && /usr/bin/echo -e "{\n    \"HttpsPort\": \"4443\",\n    \"LogLevel\": \"Debug\"\n}" > /home/safeguard/appsettings.json \
    && chown -R safeguard:safeguard /home/safeguard \
    && chown -R safeguard:safeguard /usr/share


USER safeguard
WORKDIR /home/safeguard

COPY ["SafeguardDevOpsService/bin/Release/linux-x64/publish/SafeguardDevOpsService", "/home/safeguard/"]
COPY ["docker/run-devops.sh", "/home/safeguard/run-devops.sh"]

ENTRYPOINT ["/bin/bash"]
CMD ["-c", "/home/safeguard/run-devops.sh"]
