FROM mcr.microsoft.com/dotnet/aspnet:9.0.4-noble
MAINTAINER support@oneidentity.com
ENV DOCKER_RUNNING=true

RUN apt update \
    && apt -y install nginx \
    && apt -y install sudo \
    && apt -y install psmisc \
    && apt -y install less \
    && apt -y install vim

RUN groupadd -r safeguard \
    && useradd -r -g safeguard -s /bin/bash safeguard \
    && mkdir -p /home/safeguard \
    && /usr/bin/echo -e "{\n    \"HttpsPort\": \"4443\",\n    \"LogLevel\": \"Debug\"\n}" > /home/safeguard/appsettings.json

COPY ["SafeguardDevOpsService/bin/Release/linux-x64/publish/SafeguardDevOpsService", "/home/safeguard/"]
COPY ["SafeguardDevOpsService/bin/Release/linux-musl-x64/publish/SafeguardDevOpsService.xml", "/home/safeguard"]
COPY ["SafeguardDevOpsService/bin/Release/linux-x64/publish/ClientApp", "/home/safeguard/ClientApp"]
COPY ["SafeguardDevOpsService/bin/Release/linux-x64/Certificates", "/home/safeguard/Certificates"]
COPY ["docker/run-devops.sh", "/home/safeguard/run-devops.sh"]

RUN chown -R safeguard:safeguard /home/safeguard \
    && chown -R safeguard:safeguard /usr/share
RUN echo 'safeguard ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/safeguard

USER safeguard
WORKDIR /home/safeguard

ENTRYPOINT ["/bin/bash"]
CMD ["-c", "/home/safeguard/run-devops.sh"]
